/*
   This is sample code generated by rpcgen.
   These are only templates and you can use them
   as a guideline for developing your own functions.
*/
#include "fact.h"
long int                               /* Returns a long int  */
factorial_1(int  calc_fac_1_arg, char *host) {
  CLIENT *clnt;
  long  *result_1;
                                       /* int  calc_fac_1_arg;*/
  
#ifndef DEBUG
  clnt = clnt_create (host, FACTORIAL, ONE, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror (host);
    exit (1);
  }
#endif                                 /* DEBUG */
  result_1 = calc_fac_1(&calc_fac_1_arg, clnt);
  if (result_1 == (long *) NULL) {
    clnt_perror (clnt, "call failed");
  }
#ifndef DEBUG
  clnt_destroy (clnt);
#endif                                 /* DEBUG */
  return *result_1;                    /* return value to main */
}
int
main (int argc, char *argv[]) {
  char *host;
  long int f_numb;                     /* Own declarations     */
  int      number;
  if (argc < 2) {
    printf ("usage: %s server_host\n", argv[0]);
    exit (1);
  }
  host = argv[1];
                                       /* factorial_1 (host);  */
  /*
     Replace canned call with code from previous main in program fact.c
  */
  printf("Factorial Calculator\n");
  printf("Enter a positive integer value ");
  scanf("%d", &number);
  if (number < 0)
    printf("Positive values only!\n");
  else if ((f_numb = factorial_1(number, host)) > 0)
    printf("%d! = %d\n", number, f_numb);
  else
    printf("Sorry %d! is out of my range!\n", number);
  exit (0);
}
