/*
   This is sample code generated by rpcgen.
   These are only templates and you can use them
   as a guideline for developing your own functions.
 */

#include "fact.h"
long *
calc_fac_1_svc(int *argp, struct svc_req *rqstp) {
  static long  result;
  /*
   * insert server code here
   */
  long int        total = 1, last = 0;
  int             idx;
  for (idx = *argp; idx - 1; --idx) {
    total *= idx;
    if (total <= last) {               /* Have we gone out of range? */
      result = 0;
      return (&result);
    }
    last = total;
  }
  result = total;
  return &result;
}
