/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FACT_H_RPCGEN
#define _FACT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define FACTORIAL 0x20000049
#define ONE 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALC_FAC 1
extern  long * calc_fac_1(int *, CLIENT *);
extern  long * calc_fac_1_svc(int *, struct svc_req *);
extern int factorial_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALC_FAC 1
extern  long * calc_fac_1();
extern  long * calc_fac_1_svc();
extern int factorial_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FACT_H_RPCGEN */
